// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"context"
)

type Querier interface {
	GetAllByLevel(ctx context.Context, level string) ([]BhDataLevel, error)
	GetByLevelAndName(ctx context.Context, arg GetByLevelAndNameParams) ([]BhDataLevel, error)
	GetByLevelAndReference(ctx context.Context, arg GetByLevelAndReferenceParams) ([]BhDataLevel, error)
	ListDistinctNamesByLevel(ctx context.Context, level string) ([]string, error)
}

var _ Querier = (*Queries)(nil)
